# Integración continua Travis CI

# Lenguaje de programación

language: python
python:
   - "3.5"

# Sistema operativo destino a probar

os: linux

# Distribución del sistema operativo

dist: trusty

# Requerimiento de permisos en Linux

sudo: enabled

# Compiladores a emplear

compiler: 
#  - gcc
   - clang

# Tareas a realizar antes de instalacción

before_install:

# Actualizar

  - sudo apt-get -qq update

# Configurar Git si no lo está

  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

# En caso de requerir instalar algo para la prueba

install:

# Instalar dependencias

  - sudo apt-get -y install python-all-dev python3-all-dev
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-notify2


# Tareas a ejecutar antes de nuestra prueba

before_script:

  # Instalar dependencias

  - sudo pip install requests
  - sudo pip install beautifulsoup4
  - sudo pip install configparser
  - sudo pip install pushbullet.py

  - cd programs

# Compilamos

script:

# En caso de compilación exitosa
  - cd

after_success:

  - cd ..

# Notificaciones por correo

notifications:
email: true
